- This is done for practice purpose

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
# One-hot encode 'Geography'
one_hot_encoder_geo = OneHotEncoder()
geo_encoded = one_hot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [9]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
# # Save the encoders and scaler for later use
# with open('label_encoder_gender.pkl', 'wb') as file:
#     pickle.dump(label_encoder_gender, file)

# with open('onehot_encoder_geo.pkl', 'wb') as file:
#     pickle.dump(one_hot_encoder_geo, file)

# with open('scaler.pkl', 'wb') as file:
#     pickle.dump(scaler, file)

### ANN Regression Problem statement

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

/Users/kunalsharma/Documents/Bank_Churn_Classifier/venv/lib/python3.11/site-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [15]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [16]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 982us/step - loss: 100842.0078 - mae: 100842.0078 - val_loss: 98540.6250 - val_mae: 98540.6250
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 609us/step - loss: 100397.7344 - mae: 100397.7344 - val_loss: 97280.2031 - val_mae: 97280.2031
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 596us/step - loss: 98270.3203 - mae: 98270.3203 - val_loss: 94089.5469 - val_mae: 94089.5469
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 759us/step - loss: 94827.2031 - mae: 94827.2031 - val_loss: 88692.6172 - val_mae: 88692.6172
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 598us/step - loss: 88999.6328 - mae: 88999.6328 - val_loss: 81473.9375 - val_mae: 81473.9375
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 602us/step - loss: 81023.2969 - mae: 81023.2969 - val_loss: 73331.4688 - val_mae: 73331.4688
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step - loss: 73346.9531 - mae: 73346.9531 - val_loss: 65805.1953 - val_mae: 65805.1953
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - loss: 64746.7227 - mae: 64746.7227 - val_loss: 59509.8828 - val_mae: 59509.8828
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - loss: 58503.5391 - mae: 58503.5391 - val_loss: 55267.3125 - val_mae: 55267.3125
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 647us/step - loss: 55065.6953 - mae: 55065.6953 - val_loss: 52814.8828 - val_mae: 52814.8828
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 639us/step - loss: 53279.9141 - mae: 53279.9141 - val_loss: 51696.6680 - val_mae: 51696.6680
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step - loss: 51444.4570 - mae: 51444.4570 - val_loss: 51272.5156 - val_mae: 51272.5156
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 610us/step - loss: 51364.0820 - mae: 51364.0820 - val_loss: 51094.7422 - val_mae: 51094.7422
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 596us/step - loss: 51469.8945 - mae: 51469.8945 - val_loss: 51013.2930 - val_mae: 51013.2930
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step - loss: 51221.8516 - mae: 51221.8516 - val_loss: 50950.2070 - val_mae: 50950.2070
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step - loss: 50059.9727 - mae: 50059.9727 - val_loss: 50895.8594 - val_mae: 50895.8594
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step - loss: 50365.6719 - mae: 50365.6719 - val_loss: 50843.5938 - val_mae: 50843.5938
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step - loss: 50047.8672 - mae: 50047.8672 - val_loss: 50796.9844 - val_mae: 50796.9844
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 596us/step - loss: 50131.8242 - mae: 50131.8242 - val_loss: 50756.2852 - val_mae: 50756.2852
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step - loss: 50586.6602 - mae: 50586.6602 - val_loss: 50722.1094 - val_mae: 50722.1094
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 597us/step - loss: 50223.7266 - mae: 50223.7266 - val_loss: 50687.9062 - val_mae: 50687.9062
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step - loss: 49485.4609 - mae: 49485.4609 - val_loss: 50663.3203 - val_mae: 50663.3203
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step - loss: 49683.9336 - mae: 49683.9336 - val_loss: 50635.4219 - val_mae: 50635.4219
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step - loss: 50445.0117 - mae: 50445.0117 - val_loss: 50609.3047 - val_mae: 50609.3047
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 591us/step - loss: 49578.1992 - mae: 49578.1992 - val_loss: 50575.3047 - val_mae: 50575.3047
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step - loss: 50032.9922 - mae: 50032.9922 - val_loss: 50556.6758 - val_mae: 50556.6758
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 595us/step - loss: 49483.2109 - mae: 49483.2109 - val_loss: 50525.0938 - val_mae: 50525.0938
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 587us/step - loss: 50178.8906 - mae: 50178.8906 - val_loss: 50514.1680 - val_mae: 50514.1680
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 743us/step - loss: 50294.8125 - mae: 50294.8125 - val_loss: 50488.1484 - val_mae: 50488.1484
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step - loss: 50094.9258 - mae: 50094.9258 - val_loss: 50473.9922 - val_mae: 50473.9922
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 597us/step - loss: 50508.4688 - mae: 50508.4688 - val_loss: 50459.3633 - val_mae: 50459.3633
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step - loss: 49583.0352 - mae: 49583.0352 - val_loss: 50448.0352 - val_mae: 50448.0352
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step - loss: 49309.1914 - mae: 49309.1914 - val_loss: 50431.4453 - val_mae: 50431.4453
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 594us/step - loss: 49724.9297 - mae: 49724.9297 - val_loss: 50421.5195 - val_mae: 50421.5195
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 597us/step - loss: 49323.1719 - mae: 49323.1719 - val_loss: 50413.8945 - val_mae: 50413.8945
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step - loss: 50227.0508 - mae: 50227.0508 - val_loss: 50401.7266 - val_mae: 50401.7266
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step - loss: 49646.4062 - mae: 49646.4062 - val_loss: 50384.6484 - val_mae: 50384.6484
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step - loss: 49657.3047 - mae: 49657.3047 - val_loss: 50372.8086 - val_mae: 50372.8086
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step - loss: 49495.8516 - mae: 49495.8516 - val_loss: 50367.7969 - val_mae: 50367.7969
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 591us/step - loss: 48737.8242 - mae: 48737.8242 - val_loss: 50358.5156 - val_mae: 50358.5156
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step - loss: 49734.0391 - mae: 49734.0391 - val_loss: 50363.8359 - val_mae: 50363.8359
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step - loss: 49068.8945 - mae: 49068.8945 - val_loss: 50350.8945 - val_mae: 50350.8945
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 744us/step - loss: 49540.5742 - mae: 49540.5742 - val_loss: 50355.3164 - val_mae: 50355.3164
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 591us/step - loss: 49938.6211 - mae: 49938.6211 - val_loss: 50358.3594 - val_mae: 50358.3594
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step - loss: 49573.1562 - mae: 49573.1562 - val_loss: 50348.9766 - val_mae: 50348.9766
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 587us/step - loss: 49569.1562 - mae: 49569.1562 - val_loss: 50351.1953 - val_mae: 50351.1953
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step - loss: 49425.0625 - mae: 49425.0625 - val_loss: 50342.5664 - val_mae: 50342.5664
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step - loss: 49586.4648 - mae: 49586.4648 - val_loss: 50340.0156 - val_mae: 50340.0156
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 591us/step - loss: 49336.9492 - mae: 49336.9492 - val_loss: 50340.8711 - val_mae: 50340.8711
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step - loss: 49454.7695 - mae: 49454.7695 - val_loss: 50336.8438 - val_mae: 50336.8438
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step - loss: 49230.8945 - mae: 49230.8945 - val_loss: 50329.1289 - val_mae: 50329.1289
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step - loss: 49327.7812 - mae: 49327.7812 - val_loss: 50332.6406 - val_mae: 50332.6406
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step - loss: 49869.4727 - mae: 49869.4727 - val_loss: 50330.3828 - val_mae: 50330.3828
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step - loss: 50071.1836 - mae: 50071.1836 - val_loss: 50334.3555 - val_mae: 50334.3555
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step - loss: 49687.0391 - mae: 49687.0391 - val_loss: 50325.8320 - val_mae: 50325.8320
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step - loss: 49553.4805 - mae: 49553.4805 - val_loss: 50320.0156 - val_mae: 50320.0156
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step - loss: 49090.4844 - mae: 49090.4844 - val_loss: 50327.1328 - val_mae: 50327.1328
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step - loss: 49370.2539 - mae: 49370.2539 - val_loss: 50327.5625 - val_mae: 50327.5625
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 594us/step - loss: 49432.3594 - mae: 49432.3594 - val_loss: 50324.8867 - val_mae: 50324.8867
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49322.9883 - mae: 49322.9883 - val_loss: 50324.3945 - val_mae: 50324.3945
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 739us/step - loss: 49930.3828 - mae: 49930.3828 - val_loss: 50317.6328 - val_mae: 50317.6328
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - loss: 49857.8555 - mae: 49857.8555 - val_loss: 50319.5117 - val_mae: 50319.5117
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 596us/step - loss: 49749.3359 - mae: 49749.3359 - val_loss: 50330.2031 - val_mae: 50330.2031
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 595us/step - loss: 49920.6953 - mae: 49920.6953 - val_loss: 50323.1484 - val_mae: 50323.1484
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 602us/step - loss: 49633.3008 - mae: 49633.3008 - val_loss: 50323.6016 - val_mae: 50323.6016
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 591us/step - loss: 49760.4219 - mae: 49760.4219 - val_loss: 50315.8672 - val_mae: 50315.8672
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - loss: 49846.6328 - mae: 49846.6328 - val_loss: 50320.2383 - val_mae: 50320.2383
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step - loss: 49044.4727 - mae: 49044.4727 - val_loss: 50313.9258 - val_mae: 50313.9258
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 740us/step - loss: 48668.4844 - mae: 48668.4844 - val_loss: 50324.8047 - val_mae: 50324.8047
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 600us/step - loss: 49434.0352 - mae: 49434.0352 - val_loss: 50323.5312 - val_mae: 50323.5312
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step - loss: 49568.8828 - mae: 49568.8828 - val_loss: 50321.1367 - val_mae: 50321.1367
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step - loss: 49453.1250 - mae: 49453.1250 - val_loss: 50317.9531 - val_mae: 50317.9531
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 595us/step - loss: 50139.8359 - mae: 50139.8359 - val_loss: 50320.4102 - val_mae: 50320.4102
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 585us/step - loss: 49669.6328 - mae: 49669.6328 - val_loss: 50324.8398 - val_mae: 50324.8398
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step - loss: 49092.9688 - mae: 49092.9688 - val_loss: 50327.3711 - val_mae: 50327.3711
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - loss: 49254.6719 - mae: 49254.6719 - val_loss: 50329.7383 - val_mae: 50329.7383
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step - loss: 49089.1719 - mae: 49089.1719 - val_loss: 50327.2852 - val_mae: 50327.2852
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step - loss: 49810.5156 - mae: 49810.5156 - val_loss: 50328.1641 - val_mae: 50328.1641

In [17]:
%load_ext tensorboard

In [19]:
%tensorboard --logdir {log_dir}

Reusing TensorBoard on port 6008 (pid 95794), started 0:00:05 ago. (Use '!kill 95794' to kill it.)

In [20]:
## Evaluate model on the test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - loss: 51178.2422 - mae: 51178.2422
Test MAE : 50313.92578125

In [21]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.